Implement iexec.account.approve()
iExecBlockchainComputing/iexec-sdk pull request #245
Opened 2024-04-17 15:40 UTC by abbesBenayache

2024-04-18 10:38 UTC, PierreJeanjacquot requested changes

2024-04-18 10:38 UTC, PierreJeanjacquot commented on test/lib/e2e/IExecAccountModule.test.js
> +      const spenderAddress = Wallet.createRandom().address;
use `getRandomAddress()` from utils (factorized version of this code)

2024-04-18 10:38 UTC, PierreJeanjacquot commented on test/lib/e2e/IExecAccountModule.test.js
> +    });
replace by prevent approve negative amount

2024-04-18 14:48 UTC, abbesBenayache commented on src/common/account/allowance.js
> +    const tx = await iexecContract.approve(vSpenderAddress, vAmount);
commit : 7b8b3cd71e01f80e0fb5eacf599b76e166e7df90

2024-04-18 15:53 UTC, abbesBenayache commented on docs/classes/IExecAccountModule.md
commit : cfac1c60a91f5f8d7a7ed94b7762a5f0a842f3ad

2024-04-18 15:55 UTC, abbesBenayache commented on src/common/account/allowance.js
> +    }
commit : 0395df235f3f4a19db8c0e963385d87dffebb247

2024-04-18 15:55 UTC, abbesBenayache commented on test/lib/e2e/IExecAccountModule.test.js
> +    });
commit : 00421ba2ab1b46418605f948913199bdc31432e0

2024-04-19 08:41 UTC, PierreJeanjacquot approved these changes

2024-04-19 08:48 UTC, merged