Feature/add voucher options to match orders
iExecBlockchainComputing/iexec-sdk pull request #264
Opened 2024-06-10 17:54 UTC by abbesBenayache

2024-06-17 11:42 UTC, abbesBenayache commented on src/cli/cmd/iexec-app.js
> +      if (!addressOrIndex)
this change is due to the formatter on save and can be ignored.

2024-06-17 11:42 UTC, abbesBenayache commented on src/cli/cmd/iexec-order.js
> +            : []),
this change is due to the formatter on save and can be ignored.

2024-06-17 11:42 UTC, abbesBenayache commented on src/common/market/order.js
> +
This change is due to moving the previously implemented estimateMatchOrder function to be used in matchOrder. the removed part is visible at the bottom of the changes.

2024-06-17 11:42 UTC, abbesBenayache commented on src/common/market/order.js
> -};
the previously relocated section can be found further up, as indicated in the preceding comment.

2024-06-18 07:28 UTC, PierreJeanjacquot requested changes

2024-06-18 07:30 UTC, PierreJeanjacquot commented
proposed refacto avoiding abi duplication https://github.com/iExecBlockchainComputing/iexec-sdk/pull/266

2024-06-18 09:43 UTC, PierreJeanjacquot approved these changes

2024-06-18 10:25 UTC, merged